/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetlourd;

import java.awt.event.WindowEvent;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JPanel;

/*TO DO :
*/

/*IDEA :
* à chaque action on change le Application.Panel where placement = center
*/

/**
 *
 * @author francis
 */
public class Application extends javax.swing.JFrame {

    JPanel centerPanel;
    private static Application _instance;
    /**
     * Creates new form Application
     */
    public Application() {
        initComponents();
        centerPanel = new MonProfil();
        getContentPane().add(centerPanel, java.awt.BorderLayout.CENTER);
        pack();
    }
    
    public final static  Application getInstance() throws IOException {
        if(_instance == null){
            synchronized(Application.class){
                if(Application._instance == null) {
                    Application._instance = new Application();
                }
            }
        }
        return _instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        rechercheTextField = new javax.swing.JTextField();
        rechercheComboBox = new javax.swing.JComboBox();
        rechercheButton = new javax.swing.JButton();
        deconnexionButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        footer = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Application");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(500, 50000));
        setMinimumSize(new java.awt.Dimension(500, 500));
        setName("application"); // NOI18N
        setPreferredSize(new java.awt.Dimension(500, 500));
        setResizable(false);

        header.setMaximumSize(new java.awt.Dimension(500, 90));
        header.setMinimumSize(new java.awt.Dimension(500, 90));
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rechercheTextField.setToolTipText("Rechercher un document");
        header.add(rechercheTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 128, 30));

        rechercheComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Titre", "Auteur" }));
        header.add(rechercheComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, -1, 30));

        rechercheButton.setText("Recherche");
        rechercheButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rechercheButtonMouseClicked(evt);
            }
        });
        header.add(rechercheButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, -1, 30));

        deconnexionButton.setText("Déconnexion");
        deconnexionButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deconnexionButtonMouseClicked(evt);
            }
        });
        header.add(deconnexionButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, -1, -1));

        jLabel2.setText("Bonjour " + Connexion.PSEUDO);
        header.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 340, 30));

        getContentPane().add(header, java.awt.BorderLayout.NORTH);

        footer.setLayout(new java.awt.GridLayout());

        jLabel1.setText("Adresse des membres du groupe");
        footer.add(jLabel1);

        getContentPane().add(footer, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rechercheButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rechercheButtonMouseClicked
        String toSearch = rechercheTextField.getText();
        String type = (String) rechercheComboBox.getSelectedItem();

        String recherches = Connexion.GESTIONBD.getRecherche(type, toSearch);

        System.out.println(recherches);

        String[] parties = recherches.split(",");
        String[] parties2;

        List<String[]> lRecherche = new ArrayList<>();

        //on exécute des traitements sur la chaîne retournée par la requête
        for (String party : parties) {
            //chaque ligne est un tableau de chaîne, on a donc une liste de String[]
            parties2 = party.split("-");
            lRecherche.add(parties2);
        }
    }//GEN-LAST:event_rechercheButtonMouseClicked

    private void deconnexionButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deconnexionButtonMouseClicked
        Connexion.GESTIONBD.Close();

        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));

        Connexion connexion = new Connexion();
        connexion.setVisible(true);
    }//GEN-LAST:event_deconnexionButtonMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deconnexionButton;
    private javax.swing.JPanel footer;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton rechercheButton;
    private javax.swing.JComboBox rechercheComboBox;
    private javax.swing.JTextField rechercheTextField;
    // End of variables declaration//GEN-END:variables
}
