/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetlourd;

import javax.swing.JLabel;

/**
 *
 * @author francis
 */
public class MonProfil extends javax.swing.JPanel {

    AmisPanel amisPanel;
    TravailleSurPanel travailleSurPanel;

    /**
     * Creates new form MonProfil
     */
    public MonProfil() {
        initComponents();
        
        amisPanel = new AmisPanel(Connexion.PSEUDO);
        amisScrollPane.setViewportView(amisPanel);
        
        travailleSurPanel = new TravailleSurPanel(Connexion.PSEUDO);
        travailleSurScrollPane.setViewportView(travailleSurPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        jPanel5 = new javax.swing.JPanel();
        AmisSelected = new javax.swing.JTabbedPane();
        amisScrollPane = new javax.swing.JScrollPane();
        demandeamisScrollPane = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        demandeAmisTextField = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        demandeAmisButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        creerDocumentTextField = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        ecritureComboBox = new javax.swing.JComboBox();
        lectureComboBox = new javax.swing.JComboBox();
        creerDocumentButton = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        travailleSurScrollPane = new javax.swing.JScrollPane();

        setMinimumSize(new java.awt.Dimension(500, 200));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(500, 200));
        setLayout(new java.awt.BorderLayout(15, 20));
        add(filler3, java.awt.BorderLayout.LINE_END);
        add(filler4, java.awt.BorderLayout.WEST);

        jPanel5.setLayout(new java.awt.BorderLayout());

        AmisSelected.setMinimumSize(new java.awt.Dimension(143, 100));
        AmisSelected.setName(""); // NOI18N
        AmisSelected.setPreferredSize(new java.awt.Dimension(143, 100));

        amisScrollPane.setMaximumSize(new java.awt.Dimension(25, 25));
        amisScrollPane.setName(""); // NOI18N
        AmisSelected.addTab("Mes amis", amisScrollPane);
        AmisSelected.addTab("demande d'amis", demandeamisScrollPane);

        jPanel5.add(AmisSelected, java.awt.BorderLayout.WEST);

        jPanel1.setLayout(new java.awt.GridLayout(2, 0));

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        demandeAmisTextField.setToolTipText("Entrez ici le pseudonyme de votre potentiel futur ami");
        demandeAmisTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                demandeAmisTextFieldActionPerformed(evt);
            }
        });
        jPanel2.add(demandeAmisTextField);

        jPanel6.setLayout(new java.awt.GridLayout(1, 0));
        jPanel6.add(filler1);

        demandeAmisButton.setText("Envoyer");
        jPanel6.add(demandeAmisButton);

        jPanel2.add(jPanel6);

        jPanel1.add(jPanel2);

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        creerDocumentTextField.setToolTipText("Entrez ici le titre du document que vous voulez créer");
        jPanel3.add(creerDocumentTextField);

        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        ecritureComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Public", "Amis", "Utilisateur" }));
        jPanel4.add(ecritureComboBox);

        lectureComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Public", "Amis", "Utilisateur" }));
        lectureComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lectureComboBoxActionPerformed(evt);
            }
        });
        jPanel4.add(lectureComboBox);

        creerDocumentButton.setText("Créer !");
        jPanel4.add(creerDocumentButton);

        jPanel3.add(jPanel4);

        jPanel1.add(jPanel3);

        jPanel5.add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jTabbedPane1.setToolTipText("");
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPane1.addTab("travail sur", travailleSurScrollPane);

        jPanel5.add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        add(jPanel5, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void lectureComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lectureComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lectureComboBoxActionPerformed

    private void demandeAmisTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_demandeAmisTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_demandeAmisTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane AmisSelected;
    private javax.swing.JScrollPane amisScrollPane;
    private javax.swing.JButton creerDocumentButton;
    private javax.swing.JTextField creerDocumentTextField;
    private javax.swing.JButton demandeAmisButton;
    private javax.swing.JTextField demandeAmisTextField;
    private javax.swing.JScrollPane demandeamisScrollPane;
    private javax.swing.JComboBox ecritureComboBox;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox lectureComboBox;
    private javax.swing.JScrollPane travailleSurScrollPane;
    // End of variables declaration//GEN-END:variables
}
