/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetlourd;

import java.util.List;

/**
 *
 * @author drydge
 */
public class ResultatRecherche extends javax.swing.JPanel {

    List<String> Titre;
    List<String> Auteur;
    List<String> Lecture;
    List<String> Ecriture;
    List<String> NbParticipants;
    /**
     * Creates new form ResultatRecherche
     * @param lRecherche
     */
    public ResultatRecherche(List<String[]> lRecherche) {
        System.out.println(lRecherche);
        for (String[] document : lRecherche)

        {
           // Titre.add(document[0]);
           // Auteur.add(document[1]);
            //Lecture.add(document[2]);
            //Ecriture.add(document[3]);
            //NbParticipants.add(document[4]);
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
